version: '3.9'

services:
  image-classifier:
    build: .
    container_name: image-classifier
    environment:
      MODEL_PATH: "${MODEL_PATH:-/app/model.tflite}"
      RESULTS_PATH: "${RESULTS_PATH:-/app/results.json}"
      FLASK_DEBUG: "${FLASK_DEBUG:-false}"
    ports:
      - "${FLASK_PORT:-5000}:5000"
    volumes:
      - "/mnt/docker/phineasandferb/static/uploads:/app/static/uploads"
      - "/mnt/docker/phineasandferb/model.tflite:/app/model.tflite"
      - "/mnt/docker/phineasandferb/results.json:/app/results.json"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3
