version: '3.9'

services:
  image-classifier:
    build: .
    container_name: image-classifier
    ports:
      - "${FLASK_PORT:-5000}:5000"
    volumes:
      - "${UPLOADS_PATH:-/var/lib/phineas/static/uploads}:/app/static/uploads"
      - "/path/on/host/model.tflite:${MODEL_PATH:-/app/model.tflite}"
      - "/path/on/host/results.json:${RESULTS_PATH:-/app/results.json}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3
