version: '3.9'

services:
  image-classifier:
    build: .
    container_name: image-classifier
    ports:
      - "8080:5000"
    volumes:
      - "${UPLOADS_PATH:-/var/lib/phineas/static/uploads}:/app/static/uploads"
      - "${DATA_PATH:-/var/lib/phineas/data}:/app/data"
    environment:
      - RESULTS_PATH=/app/data/results.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3
