version: "3.9"

services:
  image-classifier:
    image: vries2k/phineasorferborelse:1.0
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "5120:5000"
    environment:
      FLASK_DEBUG: "false"
    volumes:
      # Single host directory for model, results, and any other data
      - /mnt/docker/phineasandferb/data:/app/data
      # (Optional) Separate mount if you prefer uploads outside /app/data
      - /mnt/docker/phineasandferb/uploads:/app/static/uploads
    restart: unless-stopped
